<?php

use App\Provincia;
use App\Pais;
use Illuminate\Database\Seeder;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provincias = [
            ['id' => '1', 'name' => 'BUENOS AIRES', 'pais_id' => '1'],
            ['id' => '2', 'name' => 'CATAMARCA', 'pais_id' => '1'],
            ['id' => '3', 'name' => 'CHACO', 'pais_id' => '1'],
            ['id' => '4', 'name' => 'CHUBUT', 'pais_id' => '1'],
            ['id' => '5', 'name' => 'CÓRDOBA', 'pais_id' => '1'],
            ['id' => '6', 'name' => 'CORRIENTES', 'pais_id' => '1'],
            ['id' => '7', 'name' => 'ENTRE RÍOS', 'pais_id' => '1'],
            ['id' => '8', 'name' => 'FORMOSA', 'pais_id' => '1'],
            ['id' => '9', 'name' => 'JUJUY', 'pais_id' => '1'],
            ['id' => '10', 'name' => 'LA PAMPA', 'pais_id' => '1'],
            ['id' => '11', 'name' => 'LA RIOJA', 'pais_id' => '1'],
            ['id' => '12', 'name' => 'MENDOZA', 'pais_id' => '1'],
            ['id' => '13', 'name' => 'MISIONES', 'pais_id' => '1'],
            ['id' => '14', 'name' => 'NEUQUÉN', 'pais_id' => '1'],
            ['id' => '15', 'name' => 'RÍO NEGRO', 'pais_id' => '1'],
            ['id' => '16', 'name' => 'SALTA', 'pais_id' => '1'],
            ['id' => '17', 'name' => 'SAN JUAN', 'pais_id' => '1'],
            ['id' => '18', 'name' => 'SAN LUIS', 'pais_id' => '1'],
            ['id' => '19', 'name' => 'SANTA CRUZ', 'pais_id' => '1'],
            ['id' => '20', 'name' => 'SANTA FE', 'pais_id' => '1'],
            ['id' => '21', 'name' => 'SANTIAGO DEL ESTERO', 'pais_id' => '1'],
            ['id' => '22', 'name' => 'TIERRA DEL FUEGO', 'pais_id' => '1'],
            ['id' => '23', 'name' => 'TUCUMÁN', 'pais_id' => '1'],
            ['id' => '24', 'name' => 'CONCEPCIÓN', 'pais_id' => '2'],
            ['id' => '25', 'name' => 'SAN PEDRO', 'pais_id' => '2'],
            ['id' => '26', 'name' => 'CORDILLERA', 'pais_id' => '2'],
            ['id' => '27', 'name' => 'GUAIRÁ', 'pais_id' => '2'],
            ['id' => '28', 'name' => 'CAAGUAZÚ', 'pais_id' => '2'],
            ['id' => '29', 'name' => 'CAAZAPÁ', 'pais_id' => '2'],
            ['id' => '30', 'name' => 'ITAPÚA', 'pais_id' => '2'],
            ['id' => '31', 'name' => 'MISIONES', 'pais_id' => '2'],
            ['id' => '32', 'name' => 'PARAGUARÍ', 'pais_id' => '2'],
            ['id' => '33', 'name' => 'ALTO PARANÁ', 'pais_id' => '2'],
            ['id' => '34', 'name' => 'CENTRAL', 'pais_id' => '2'],
            ['id' => '35', 'name' => 'ÑEEMBUCÚ', 'pais_id' => '2'],
            ['id' => '36', 'name' => 'AMAMBAY', 'pais_id' => '2'],
            ['id' => '37', 'name' => 'CANINDEYÚ', 'pais_id' => '2'],
            ['id' => '38', 'name' => 'PRESIDENTE HAYES', 'pais_id' => '2'],
            ['id' => '39', 'name' => 'BOQUERÓN', 'pais_id' => '2'],
            ['id' => '40', 'name' => 'ALTO PARAGUAY', 'pais_id' => '2'],
            ['id' => '41', 'name' => 'ACRE', 'pais_id' => '3'],
            ['id' => '42', 'name' => 'ALAGOAS', 'pais_id' => '3'],
            ['id' => '43', 'name' => 'AMAPÁ', 'pais_id' => '3'],
            ['id' => '44', 'name' => 'AMAZONAS', 'pais_id' => '3'],
            ['id' => '45', 'name' => 'BAHÍA', 'pais_id' => '3'],
            ['id' => '46', 'name' => 'CEARÁ', 'pais_id' => '3'],
            ['id' => '47', 'name' => 'DISTRITO FEDERAL', 'pais_id' => '3'],
            ['id' => '48', 'name' => 'ESPÍRITO SANTO', 'pais_id' => '3'],
            ['id' => '49', 'name' => 'GOIÁS', 'pais_id' => '3'],
            ['id' => '50', 'name' => 'MARANHÃO', 'pais_id' => '3'],
            ['id' => '51', 'name' => 'MATO GROSSO', 'pais_id' => '3'],
            ['id' => '52', 'name' => 'MATO GROSSO DEL SUR', 'pais_id' => '3'],
            ['id' => '53', 'name' => 'MINAS GERAIS', 'pais_id' => '3'],
            ['id' => '54', 'name' => 'PARÁ', 'pais_id' => '3'],
            ['id' => '55', 'name' => 'PARAÍBA', 'pais_id' => '3'],
            ['id' => '56', 'name' => 'PARANÁ', 'pais_id' => '3'],
            ['id' => '57', 'name' => 'PERNAMBUCO', 'pais_id' => '3'],
            ['id' => '58', 'name' => 'PIAUÍ', 'pais_id' => '3'],
            ['id' => '59', 'name' => 'RÍO DE JANEIRO', 'pais_id' => '3'],
            ['id' => '60', 'name' => 'RÍO GRANDE DEL NORTE', 'pais_id' => '3'],
            ['id' => '61', 'name' => 'RÍO GRANDE DEL SUR', 'pais_id' => '3'],
            ['id' => '62', 'name' => 'RONDONIA', 'pais_id' => '3'],
            ['id' => '63', 'name' => 'RORAIMA', 'pais_id' => '3'],
            ['id' => '64', 'name' => 'SANTA CATARINA', 'pais_id' => '3'],
            ['id' => '65', 'name' => 'SÃO PAULO', 'pais_id' => '3'],
            ['id' => '66', 'name' => 'SERGIPE', 'pais_id' => '3'],
            ['id' => '67', 'name' => 'TOCANTINS', 'pais_id' => '3'],
            ['id' => '68', 'name' => 'ALABAMA', 'pais_id' => '4'],
            ['id' => '69', 'name' => 'ALASKA', 'pais_id' => '4'],
            ['id' => '70', 'name' => 'ARIZONA', 'pais_id' => '4'],
            ['id' => '71', 'name' => 'ARKANSAS', 'pais_id' => '4'],
            ['id' => '72', 'name' => 'CALIFORNIA', 'pais_id' => '4'],
            ['id' => '73', 'name' => 'CAROLINA DEL NORTE', 'pais_id' => '4'],
            ['id' => '74', 'name' => 'CAROLINA DEL SUR', 'pais_id' => '4'],
            ['id' => '75', 'name' => 'COLORADO', 'pais_id' => '4'],
            ['id' => '76', 'name' => 'CONNECTICUT', 'pais_id' => '4'],
            ['id' => '77', 'name' => 'DAKOTA DEL NORTE', 'pais_id' => '4'],
            ['id' => '78', 'name' => 'DAKOTA DEL SUR', 'pais_id' => '4'],
            ['id' => '79', 'name' => 'DELAWARE', 'pais_id' => '4'],
            ['id' => '80', 'name' => 'FLORIDA', 'pais_id' => '4'],
            ['id' => '81', 'name' => 'GEORGIA', 'pais_id' => '4'],
            ['id' => '82', 'name' => 'HAWÁI', 'pais_id' => '4'],
            ['id' => '83', 'name' => 'IDAHO', 'pais_id' => '4'],
            ['id' => '84', 'name' => 'ILLINOIS', 'pais_id' => '4'],
            ['id' => '85', 'name' => 'INDIANA', 'pais_id' => '4'],
            ['id' => '86', 'name' => 'IOWA', 'pais_id' => '4'],
            ['id' => '87', 'name' => 'KANSAS', 'pais_id' => '4'],
            ['id' => '88', 'name' => 'KENTUCKY', 'pais_id' => '4'],
            ['id' => '89', 'name' => 'LUISIANA', 'pais_id' => '4'],
            ['id' => '90', 'name' => 'MAINE', 'pais_id' => '4'],
            ['id' => '91', 'name' => 'MARYLAND', 'pais_id' => '4'],
            ['id' => '92', 'name' => 'MASSACHUSETTS', 'pais_id' => '4'],
            ['id' => '93', 'name' => 'MICHIGAN', 'pais_id' => '4'],
            ['id' => '94', 'name' => 'MINNESOTA', 'pais_id' => '4'],
            ['id' => '95', 'name' => 'MISISIPI', 'pais_id' => '4'],
            ['id' => '96', 'name' => 'MISURI', 'pais_id' => '4'],
            ['id' => '97', 'name' => 'MONTANA', 'pais_id' => '4'],
            ['id' => '98', 'name' => 'NEBRASKA', 'pais_id' => '4'],
            ['id' => '99', 'name' => 'NEVADA', 'pais_id' => '4'],
            ['id' => '100', 'name' => 'NUEVA JERSEY', 'pais_id' => '4'],
            ['id' => '101', 'name' => 'NUEVA YORK', 'pais_id' => '4'],
            ['id' => '102', 'name' => 'NUEVO HAMPSHIRE', 'pais_id' => '4'],
            ['id' => '103', 'name' => 'NUEVO MÉXICO', 'pais_id' => '4'],
            ['id' => '104', 'name' => 'OHIO', 'pais_id' => '4'],
            ['id' => '105', 'name' => 'OKLAHOMA', 'pais_id' => '4'],
            ['id' => '106', 'name' => 'OREGÓN', 'pais_id' => '4'],
            ['id' => '107', 'name' => 'PENSILVANIA', 'pais_id' => '4'],
            ['id' => '108', 'name' => 'RHODE ISLAND', 'pais_id' => '4'],
            ['id' => '109', 'name' => 'TENNESSEE', 'pais_id' => '4'],
            ['id' => '110', 'name' => 'TEXAS', 'pais_id' => '4'],
            ['id' => '111', 'name' => 'UTAH', 'pais_id' => '4'],
            ['id' => '112', 'name' => 'VERMONT', 'pais_id' => '4'],
            ['id' => '113', 'name' => 'VIRGINIA', 'pais_id' => '4'],
            ['id' => '114', 'name' => 'VIRGINIA OCCIDENTAL', 'pais_id' => '4'],
            ['id' => '115', 'name' => 'WASHINGTON', 'pais_id' => '4'],
            ['id' => '116', 'name' => 'WISCONSIN', 'pais_id' => '4'],
            ['id' => '117', 'name' => 'WYOMING', 'pais_id' => '4'],
            ['id' => '118', 'name' => 'ASUNCIÓN', 'pais_id' => '2'],
            ['id' => '999', 'name' => 'BOLIVIA', 'pais_id' => '4']
        ];

        foreach ($provincias as $una_provincia) {
            Provincia::create($una_provincia);
        }
    }
}
